rikudou_dynamo_db_cache:
    table: '%app.dynamo.cache_table%'
    # Use DynamoDB by default for cache & sessions
    replace_default_adapter: false
    client_config:
        region: '%env(AWS_REGION)%'
    encoder:
        service: App\Service\Base64CacheItemEncoder
