# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.mode: '%env(APP_MODE)%'
    app.signing_secret: '%env(SLACK_SIGNING_SECRET)%'
    app.bot_token: '%env(resolve:SLACK_BOT_TOKEN)%'
    app.openai_api_key: '%env(OPENAI_API_KEY)%'
    app.dynamo.channel_mode_table: '%env(CHANNEL_MODES_TABLE)%'
    app.chatgpt.system_message: '%env(CHAT_GPT_SYSTEM_MESSAGE)%'
    app.bot.default_channel_mode: '%env(DEFAULT_CHANNEL_MODE)%'
    app.bot.welcome_message: '%env(WELCOME_MESSAGE)%'
    app.rate_limit.per_user: '%env(int:PER_USER_DAILY_LIMIT)%'
    app.rate_limit.global: '%env(int:TOTAL_DAILY_LIMIT)%'
    app.dynamo.user_settings_table: '%env(USER_SETTINGS_TABLE)%'
    app.dynamo.cache_table: '%env(DYNAMODB_CACHE_TABLE)%'
    app.redis.host: '%env(REDIS_HOST)%'
    app.messenger.dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
    app.slack.validate_signature: '%env(bool:VALIDATE_SIGNATURE)%'
    app.openai.timeout: '%env(int:OPENAI_TIMEOUT)%'
    app.openai.model: '%env(OPENAI_MODEL)%'
    app.openai.organization_id: '%env(OPENAI_ORGANIZATION_ID)%'
    app.bot.reply_mode: '%env(enum:App\Enum\ReplyMode:REPLY_MODE)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    Bref\Symfony\Messenger\Service\Sqs\SqsConsumer:
        public: true
        arguments:
            $transportName: 'async'
            $partialBatchFailure: false

    AsyncAws\DynamoDb\DynamoDbClient:
        arguments:
            - region: '%env(AWS_REGION)%'

    Redis:
        class: Redis
        calls:
            - connect: ['%app.redis.host%']

    app.cache.service: '@rikudou.dynamo_cache.cache'
